#!/bin/bash
# ---
# RightScript Name: KUBE Set Tags
# Inputs:
#   KUBE_CLUSTER:
#     Category: Application
#     Description: Cluster name for the cluster. Must be unique per account.
#     Input Type: single
#     Required: true
#     Advanced: false
#   KUBE_ROLE:
#     Category: Application
#     Input Type: single
#     Required: true
#     Advanced: false
#     Possible Values:
#     - text:master
#     - text:node
#   MY_IP:
#     Category: RightScale
#     Input Type: single
#     Required: true
#     Advanced: true
#     Default: env:PRIVATE_IP
#   SERVER_NAME:
#     Category: RightScale
#     Input Type: single
#     Required: true
#     Advanced: true
#     Default: env:RS_SERVER_NAME
# Attachments:
# - tagging.sh
# ...

# shellcheck source=attachments/tagging.sh
source "$RS_ATTACH_DIR"/tagging.sh

tag_and_verify "kube:ip=$MY_IP"
tag_and_verify "kube:role=$KUBE_ROLE"
tag_and_verify "kube:cluster=$KUBE_CLUSTER"
